[project]
name = "esiqie-dictamenes"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "flet[all]>=0.86.5",
    "httpx>=0.28.1",
    "python-dotenv>=1.2.3",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.flet.app]
path = "src"
module = "main.py"
